[tool.towncrier]
directory = "doc/news"
package = "lsst.ts.gis"
package_dir = "python"
filename = "doc/version-history.rst"
name = "ts_gis"
issue_format = "`{issue} <https://jira.lsstcorp.org/{issue}>`_"

