{% set data= load_setup_py_data() %}
package:
    name: ts-gis
    version: {{ data.get('version') }}

source:
    path: ../

build:
    noarch: python
    script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
    entry_points:
        - run_gis = lsst.ts.gis.cli:execute_csc
    script_env:
        - PATH
        - PYTHONPATH
        - LD_LIBRARY_PATH
        - OSPL_HOME
        - PYTHON_BUILD_VERSION
        - PYTHON_BUILD_LOCATION
        - LSST_DDS_DOMAIN
        - TS_CONFIG_OCS_DIR
        - LSST_SITE

test:
    requires:
        - ts-conda-build =0.3
        - ts-dds
        - ts-idl {{ idl_version }}
        - ts-salobj {{ salobj_version }}
        - pymodbus >3
        - sshtunnel
    source_files:
        - python
        - bin
        - tests
        - setup.cfg
        - pyproject.toml
    commands:
        - py.test

requirements:
    host:
        - python {{ python }}
        - pip
        - setuptools_scm
        - setuptools
        - pytest-runner
    build:
        - python {{ python }}
        - setuptools_scm
        - setuptools
        - ts-conda-build =0.3
        - pymodbus
        - sshtunnel
    run:
        - python {{ python }}
        - setuptools
        - setuptools_scm
        - ts-salobj
        - ts-idl
        - pymodbus
        - sshtunnel
