{% set data= load_setup_py_data() %}
package:
    name: ts-gis
    version: {{ data.get('version') }}

source:
    path: ../

build:
    noarch: python
    script: {{PYTHON}} -m pip install --no-deps --ignore-installed .


test:
    requires:
        - ts-idl {{ idl_version }}
        - ts-salobj {{ salobj_version }}
        - ts-conda-build =0.4
    source_files:
        - python
        - bin
        - tests
        - pyproject.toml
    commands:
        - pytest

requirements:
    host:
        - python {{python}}
        - setuptools_scm
        - setuptools
    build:
        - python {{python}}
        - setuptools_scm
        - setuptools
    run:
        - python {{python}}
        - ts-salobj
        - ts-idl
        - pymodbus >=3.5, <=3.6
        - aiohttp =3.8
        - sshtunnel
